### ISSUE TITLE
Error (v3.0): Could not find custom field

### ISSUE THREAD

**Issue by rollox** [compucorp/uk.co.compucorp.civicrm.giftaid#48]
When installing extension on a clean DB I get...

"Could not find custom field for custom.civicrm_value_gift_aid_submission.eligible_for_gift_aid, civicrm_value_gift_aid_submission, eligible_for_gift_aid"

Extension 3.0 stable (2017-06-21)
CiviCRM 4.7.21
Drupal 7
PHP 5.6.31
MySQL 5.6.37

**Comment by rollox** [comment]
$backTrace = 
	#0 /.../public_html/sites/all/modules/civicrm/CRM/Core/Error.php(378): CRM_Core_Error::backtrace("backTrace", TRUE) 
	#1 /.../public_html/sites/all/modules/civicrm/CRM/Utils/Migrate/Import.php(456): CRM_Core_Error::fatal("Could not find custom field for custom.civicrm_value_gift_aid_submission.elig...") 
	#2 /.../public_html/sites/all/modules/civicrm/CRM/Utils/Migrate/Import.php(85): CRM_Utils_Migrate_Import->profileFields(Object(SimpleXMLElement), (Array:3)) 
	#3 /.../public_html/sites/all/modules/civicrm/CRM/Utils/Migrate/Import.php(58): CRM_Utils_Migrate_Import->runXmlElement(Object(SimpleXMLElement)) 
	#4 /.../public_html/sites/all/extensions/uk.co.compucorp.civicrm.giftaid-3.0/civigiftaid.php(33): CRM_Utils_Migrate_Import->run("/.../public_html/sites/all/extensions/uk.co.compucorp.civic...") 
	#5 /.../public_html/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(76): civigiftaid_civicrm_install() 
	#6 /.../public_html/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(48): CRM_Extension_Manager_Module->callHook(Object(CRM_Extension_Info), "install") 
	#7 /.../public_html/sites/all/modules/civicrm/CRM/Extension/Manager.php(229): CRM_Extension_Manager_Module->onPreInstall(Object(CRM_Extension_Info)) 
	#8 /.../public_html/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php(181): CRM_Extension_Manager->install((Array:1)) 
	#9 /.../public_html/sites/all/modules/civicrm/CRM/Core/Form.php(447): CRM_Admin_Form_Extensions->postProcess() 
	#10 /.../public_html/sites/all/modules/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess() 
	#11 /.../public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next") 
	#12 /.../public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next") 
	#13 /.../public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next") 
	#14 /.../public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("next") 
	#15 /.../public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(384): CRM_Core_Controller->run() 
	#16 /.../public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(168): CRM_Core_Page_Basic->edit(1, NULL) 
	#17 /.../public_html/sites/all/modules/civicrm/CRM/Admin/Page/Extensions.php(121): CRM_Core_Page_Basic->run() 
	#18 /.../public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(310): CRM_Admin_Page_Extensions->run((Array:3), NULL) 
	#19 /.../public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:13)) 
	#20 /.../public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3)) 
	#21 /.../public_html/sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke((Array:3)) 
	#22 [internal function](): civicrm_invoke("admin", "extensions") 
	#23 /.../public_html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2)) 
	#24 /.../public_html/index.php(21): menu_execute_active_handler() 
	#25 {main}

**Comment by rollox** [comment]
Must have had fields already in database that were colliding with the new ones as deleting all Gift Aid related fields let this module install properly.
